### ISSUE TITLE
Get os access violation reading error when training on windows

### ISSUE THREAD

**Issue by lsnuwafi** [nemanja-m/super-mario-agent#5]
Got os access violation reading error when try to train my model use multi-threading.
When the program try to call the pyd.
I am using 64-win10, py3.7, and NES-PY 7.0.1
File "D:\py37\lib\site-packages\nes_py\nes_env.py", line 259, in reset
self._restore()
File "D:\py37\lib\site-packages\nes_py\nes_env.py", line 221, in _restore
_LIB.Restore(self._env)
OSError: exception: access violation reading 0x000001DFDBDC8E30

**Comment by nemanja-m** [comment]
I haven't tried to train an agent on Windows :/ but it looks like it's `nes_py` issue.
